package io.jxunix.mapper;

import io.jxunix.domain.PurchaseReturnOrder;
import io.jxunix.domain.PurchaseReturnOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PurchaseReturnOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int countByExample(PurchaseReturnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int deleteByExample(PurchaseReturnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int insert(PurchaseReturnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int insertSelective(PurchaseReturnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    List<PurchaseReturnOrder> selectByExample(PurchaseReturnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    PurchaseReturnOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") PurchaseReturnOrder record, @Param("example") PurchaseReturnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int updateByExample(@Param("record") PurchaseReturnOrder record, @Param("example") PurchaseReturnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int updateByPrimaryKeySelective(PurchaseReturnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int updateByPrimaryKey(PurchaseReturnOrder record);
}