package io.jxunix.mapper;

import io.jxunix.domain.SaleReturnOrder;
import io.jxunix.domain.SaleReturnOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleReturnOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int countByExample(SaleReturnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int deleteByExample(SaleReturnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int insert(SaleReturnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int insertSelective(SaleReturnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    List<SaleReturnOrder> selectByExample(SaleReturnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    SaleReturnOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") SaleReturnOrder record, @Param("example") SaleReturnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int updateByExample(@Param("record") SaleReturnOrder record, @Param("example") SaleReturnOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int updateByPrimaryKeySelective(SaleReturnOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_return_order
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int updateByPrimaryKey(SaleReturnOrder record);
}