package io.jxunix.mapper;

import io.jxunix.domain.Shopper;
import io.jxunix.domain.ShopperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopper
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int countByExample(ShopperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopper
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int deleteByExample(ShopperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopper
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopper
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int insert(Shopper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopper
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int insertSelective(Shopper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopper
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    List<Shopper> selectByExample(ShopperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopper
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    Shopper selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopper
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") Shopper record, @Param("example") ShopperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopper
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int updateByExample(@Param("record") Shopper record, @Param("example") ShopperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopper
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int updateByPrimaryKeySelective(Shopper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopper
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    int updateByPrimaryKey(Shopper record);
}