package io.jxunix.domain;

public class Shopper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopper.id
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopper.name
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopper.sex
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopper.mobile
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    private Integer mobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopper.id
     *
     * @return the value of shopper.id
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopper.id
     *
     * @param id the value for shopper.id
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopper.name
     *
     * @return the value of shopper.name
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopper.name
     *
     * @param name the value for shopper.name
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopper.sex
     *
     * @return the value of shopper.sex
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopper.sex
     *
     * @param sex the value for shopper.sex
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopper.mobile
     *
     * @return the value of shopper.mobile
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    public Integer getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopper.mobile
     *
     * @param mobile the value for shopper.mobile
     *
     * @mbggenerated Mon Jun 20 12:35:50 CST 2016
     */
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }
}